CREATE TABLE IF NOT EXISTS articles (
  id VARCHAR (10) PRIMARY KEY, 
  name VARCHAR (20) NOT NULL,
  description VARCHAR (200) NOT NULL,
  price NUMERIC (6, 2) NOT NULL,
  model VARCHAR (10) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);